name: Daily Starbucks Collection

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 1 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소 체크아웃
      - uses: actions/checkout@v4

      # 2. Python 설정
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # 3. Python 패키지 설치
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 lxml selenium webdriver_manager

      # 4. 스크립트 실행
      - name: Run Starbucks Location Script
        run: |
          python starbucks-location.py
          python starbucks-location2.py

      - name: Run Starbucks Details Script
        run: |
          retry() {
            for i in {1..3}; do
              "$@" && break || sleep 10
            done
          }
          retry python starbucks-details-busan.py
          retry python starbucks-details-chungbuk.py
          retry python starbucks-details-chungnam.py
          retry python starbucks-details-daegu.py
          retry python starbucks-details-daejeon.py
          retry python starbucks-details-gangwon.py
          retry python starbucks-details-gwangju.py
          retry python starbucks-details-gyeongbuk.py
          retry python starbucks-details-gyeonggi.py
          retry python starbucks-details-gyeongnam.py
          retry python starbucks-details-incheon.py
          retry python starbucks-details-jeju.py
          retry python starbucks-details-jeolbuk.py
          retry python starbucks-details-jeolnam.py
          retry python starbucks-details-seoul.py
          retry python starbucks-details-ulsan.py

      # 5. 생성된 데이터 파일 커밋
      - name: Commit changes
        run: |
          git config --global user.email "webstoryboy@naver.com"
          git config --global user.name "websseu"
          git add location/**/*.json  details/**/*.json || echo "No JSON files to add"
          git commit -m "스타벅스 데이터 업데이트 - $(date +"%Y-%m-%d")" || echo "No changes to commit"

      # 6. 변경사항 푸시
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
